/*$file${components::SystemManagement::components::wifi::.::Wifi.h} vvvvvvvv*/
/*
* Model: kahayag_suga.qm
* File:  ${components::SystemManagement::components::wifi::.::Wifi.h}
*
* This code has been generated by QM 4.5.0 (https://www.state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*/
/*$endhead${components::SystemManagement::components::wifi::.::Wifi.h} ^^^^^*/
#ifndef __KAHAYAG_WIFI_H__
#define __KAHAYAG_WIFI_H__

#include "esp_event_loop.h"

#define MAX_WIFI_HOOK           (1)

typedef esp_err_t (*Wifi_HookFunction)(void * ctx, system_event_t * event);

/*$declare${components::SystemManagement::components::wifi::Wifi_ctor} vvvvv*/
/*${components::SystemManagement::components::wifi::Wifi_ctor} .............*/
QHsm * Wifi_ctor(QHsm * parent);
/*$enddecl${components::SystemManagement::components::wifi::Wifi_ctor} ^^^^^*/
/*$declare${components::SystemManagement::components::wifi::Wifi_AddHook} vv*/
/*${components::SystemManagement::components::wifi::Wifi_AddHook} ..........*/
esp_err_t Wifi_AddHook(Wifi_HookFunction pfn);
/*$enddecl${components::SystemManagement::components::wifi::Wifi_AddHook} ^^*/
/*$declare${components::SystemManagement::components::wifi::Wifi_RemoveHook} */
/*${components::SystemManagement::components::wifi::Wifi_RemoveHook} .......*/
esp_err_t Wifi_RemoveHook(Wifi_HookFunction pfn);
/*$enddecl${components::SystemManagement::components::wifi::Wifi_RemoveHook} */

#endif /* __KAHAYAG_WIFI_H__ */