/*$file${components::InputOutput::.::InOut.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: kahayag_suga.qm
* File:  ${components::InputOutput::.::InOut.h}
*
* This code has been generated by QM 4.5.0 (https://www.state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*/
/*$endhead${components::InputOutput::.::InOut.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#ifndef IN_OUT_H
#define IN_OUT_H

#define INOUT_TICK_INTERVAL_MS        (10)

typedef enum {
    INPUT_ID_ONE = 0,

    N_INPUT_ID
} INPUT_ID_T;

/*$declare${components::InputOutput::Events::InputEvt} vvvvvvvvvvvvvvvvvvvvv*/
/*${components::InputOutput::Events::InputEvt} .............................*/
typedef struct {
/* protected: */
    QEvt super;

/* private: */
    uint32_t id;
} InputEvt;
/*$enddecl${components::InputOutput::Events::InputEvt} ^^^^^^^^^^^^^^^^^^^^^*/

/*$declare${components::InputOutput::AO_InOut} vvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
extern QActive * const AO_InOut;
/*$enddecl${components::InputOutput::AO_InOut} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

/*$declare${components::InputOutput::InOut_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*${components::InputOutput::InOut_ctor} ...................................*/
void InOut_ctor(void);
/*$enddecl${components::InputOutput::InOut_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

#endif /* IN_OUT_H */