/*$file${.::control.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: bdcMotor.qm
* File:  ${.::control.c}
*
* This code has been generated by QM 4.5.0 (https://www.state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*/
/*$endhead${.::control.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#include "qpc.h"
#include "control.h"
#include "esp_log.h"

/*$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/* Check for the minimum required QP version */
#if (QP_VERSION < 650U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpc version 6.5.0 or higher required
#endif
/*$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*$define${control::ctrl_pid_execute} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*${control::ctrl_pid_execute} .............................................*/
esp_err_t ctrl_pid_execute(pid_ctrl_record_t * pCtrlRec) {
    esp_err_t retval = ESP_OK;

    if(pCtrlRec != NULL) {
        /* calculate error */
        pCtrlRec->q16_e = pCtrlRec->q16_reference - pCtrlRec->q16_feedback;
        /* calculate output command */
        pCtrlRec->q16_u = pCtrlRec->q16_u1 +
                fix16_mul(pCtrlRec->q16_coeff_a, pCtrlRec->q16_e) +
                fix16_mul(pCtrlRec->q16_coeff_b, pCtrlRec->q16_e1) +
                fix16_mul(pCtrlRec->q16_coeff_c, pCtrlRec->q16_e2);
        /* Output shall be within limit */
        if(pCtrlRec->q16_u > pCtrlRec->q16_highLimit) {
            pCtrlRec->q16_u = pCtrlRec->q16_highLimit;
        } else if(pCtrlRec->q16_u < pCtrlRec->q16_lowLimit) {
            pCtrlRec->q16_u = pCtrlRec->q16_lowLimit;
        }
        /* Store necessary information for the next control iteration */
        pCtrlRec->q16_u1 = pCtrlRec->q16_u;
        pCtrlRec->q16_e2 = pCtrlRec->q16_e1;
        pCtrlRec->q16_e1 = pCtrlRec->q16_e;
    } else {
        retval = ESP_ERR_INVALID_ARG;
    }

    return (retval);
}
/*$enddef${control::ctrl_pid_execute} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
