#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := motorCtrl
CFLAGS += -DQ_SPY

include $(KAHAYAG_PATH)/firmware/project.mk
