/*$file${.::include::bdcMotor.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: bdcMotor.qm
* File:  ${.::include::bdcMotor.h}
*
* This code has been generated by QM 4.5.0 (https://www.state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*/
/*$endhead${.::include::bdcMotor.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#ifndef _BDC_MOTOR_H_
#define _BDC_MOTOR_H_

#include "qpc.h"
#include "fix16.h"

/*!
 * @brief Selection of all available Motor ID
 */
typedef enum {
    MOTOR_ID_ONE = 0,   /*!< Motor 1 */
    MOTOR_ID_TWO,       /*!< Motor 2 */
    MOTOR_ID_THREE,     /*!< Motor 3 */
    MOTOR_ID_FOUR,      /*!< Motor 4 */
    MOTOR_ID_MAX
} motor_id_t;

// MOTOR EVENT TAGS
#define EVENT_MOTOR_POSITION_REACHED            (0x00)
#define EVENT_MOTOR_STOPPED                     (0x01)

/*$declare${bdcMotor::AO_bdcMotor[MOTOR_ID_MAX]} vvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/* opaque pointer to motor Active Object */
extern QActive * const AO_bdcMotor[MOTOR_ID_MAX];
/*$enddecl${bdcMotor::AO_bdcMotor[MOTOR_ID_MAX]} ^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

/* helper macro to provide the ID of motor "me_" */
#define MOTOR_ID(me_)    ((uint8_t)((me_) - l_bdcMotor))

/*$declare${bdcMotor::bdc_motor_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*${bdcMotor::bdc_motor_ctor} ..............................................*/
void bdc_motor_ctor(void);
/*$enddecl${bdcMotor::bdc_motor_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*$declare${bdcMotor::bdc_motor_move} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*${bdcMotor::bdc_motor_move} ..............................................*/
esp_err_t bdc_motor_move(
    motor_id_t id,
    fix16_t q16_refPosition,
    fix16_t q16_jogSpeed,
    void const * const sender);
/*$enddecl${bdcMotor::bdc_motor_move} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*$declare${bdcMotor::bdc_motor_run} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*${bdcMotor::bdc_motor_run} ...............................................*/
esp_err_t bdc_motor_run(
    motor_id_t id,
    fix16_t q16_refSpeed,
    void const * const sender);
/*$enddecl${bdcMotor::bdc_motor_run} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*$declare${bdcMotor::bdc_motor_stop} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*${bdcMotor::bdc_motor_stop} ..............................................*/
esp_err_t bdc_motor_stop(motor_id_t id, void const * const sender);
/*$enddecl${bdcMotor::bdc_motor_stop} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*$declare${bdcMotor::bdc_motor_get_speed} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*${bdcMotor::bdc_motor_get_speed} .........................................*/
fix16_t bdc_motor_get_speed(motor_id_t id);
/*$enddecl${bdcMotor::bdc_motor_get_speed} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*$declare${bdcMotor::bdc_motor_get_position} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*${bdcMotor::bdc_motor_get_position} ......................................*/
fix16_t bdc_motor_get_position(motor_id_t id);
/*$enddecl${bdcMotor::bdc_motor_get_position} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*$declare${bdcMotor::bdc_motor_get_current} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*${bdcMotor::bdc_motor_get_current} .......................................*/
fix16_t bdc_motor_get_current(motor_id_t id);
/*$enddecl${bdcMotor::bdc_motor_get_current} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

#endif /* _BDC_MOTOR_H_ */