/*$file${.::include::bdcMotor.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: bdcMotor.qm
* File:  ${.::include::bdcMotor.h}
*
* This code has been generated by QM 4.5.0 (https://www.state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*/
/*$endhead${.::include::bdcMotor.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#ifndef _BDC_MOTOR_H_
#define _BDC_MOTOR_H_

#include "qpc.h"
#include "fix16.h"

/*!
 * @brief Selection of all available Motor ID
 */
typedef enum {
    MOTOR_ID_ONE = 0,   /*!< Motor 1 */
    MOTOR_ID_TWO,       /*!< Motor 2 */
    MOTOR_ID_THREE,     /*!< Motor 3 */
    MOTOR_ID_FOUR,      /*!< Motor 4 */
    MOTOR_ID_MAX
} motor_id_t;

/*$declare${bdcMotor::AO_bdcMotor[MOTOR_ID_MAX]} vvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/* opaque pointer to motor Active Object */
extern QActive * const AO_bdcMotor[MOTOR_ID_MAX];
/*$enddecl${bdcMotor::AO_bdcMotor[MOTOR_ID_MAX]} ^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

/* helper macro to provide the ID of motor "me_" */
#define MOTOR_ID(me_)    ((uint8_t)((me_) - l_bdcMotor))

/*$declare${bdcMotor::bdc_motor_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*${bdcMotor::bdc_motor_ctor} ..............................................*/
void bdc_motor_ctor(void);
/*$enddecl${bdcMotor::bdc_motor_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

#endif /* _BDC_MOTOR_H_ */