/*$file${.::priorityList.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: get-started.qm
* File:  ${.::priorityList.h}
*
* This code has been generated by QM 4.5.0 (https://www.state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*/
/*$endhead${.::priorityList.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#ifndef PRIORITY_LIST_H
#define PRIORITY_LIST_H

enum task_priority {
    PRIORITY_QSPY_TX = tskIDLE_PRIORITY + 1,
    PRIORITY_QSPY_RX,
    PRIORITY_TEST,

    PRIORITY_MAX
};

/* freeRTOS task priority should be less than configMAX_PRIORITIES
 * as defined in FreeRTOSConfig.h
 */
Q_ASSERT_COMPILE(PRIORITY_MAX < configMAX_PRIORITIES);

#endif /* PRIORITY_LIST_H */